app:
    resource: "@AppBundle/Controller/"
    type:     annotation

contact:
  path: /contact
  defaults: { _controller: AppBundle:Contact:renderForm }

submit_contact:
  path: /submit
  defaults: { _controller: AppBundle:Contact:submitForm}
  methods: [ POST ]